services:
  - type: web
    name: bun-crud-app
    runtime: docker
    plan: free
    buildCommand: docker build -t bun-app .
    startCommand: docker run -p 10000:3000 bun-app
    envVars:
      - key: PORT
        value: 3000